### ISSUE TITLE
Get AUTHENTICATION_ERROR when calling authenticateAES

### ISSUE THREAD

**Issue by JKorsten** [piotrekwitkowski/LibraryReader#1]
I'm using your project to see if I can read my encrypted NFC DESFire EV2 card.
I really like your code, it's really complete and very well documented. Only issue I currently have is that I can't authenticate my  card.

It goes into the authenticateAES function from the DESFireReader class and it get to the point where the code sends D but there I get an AE exception.
I don't know why this is, the AES Key I'm using is correct because I used it before in other apps and there it works. But now it doesn't.

I've tried to flip it (because I needed that for the AID as well (010203 needed to become 030201) but for the key it doesn't matter. I can't give you more information because of course it is card specific.

Hope you can help.

**Comment by piotrekwitkowski** [comment]
Glad you liked it! I assume your card recognized correctly in the reader app (that it is a "PHYSICAL" card and not the HCE-based one). 
- Is your card protected with the PICC Master Key?
- Do you have just one key per Application?
- Could you upload the logcat's output or a screenshot from the reader app (maybe you can remove your sensitive data somehow)?

**Comment by JKorsten** [comment]
Yes it recognised  it correctly.
I never needed the PICC Master Key before.
The application I'm using only has one read key which I'm using.

`2021-04-20 15:15:25.413 27336-27373/com.piotrekwitkowski.libraryreader I/MainActivity: onTagDiscovered()
2021-04-20 15:15:25.414 27336-27373/com.piotrekwitkowski.libraryreader I/LibraryReader: processTag()
2021-04-20 15:15:25.415 27336-27373/com.piotrekwitkowski.libraryreader I/StudentId: getStudentId()
2021-04-20 15:15:25.415 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: connect()
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/StudentId: getIdForm()
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: getHistoricalBytes()
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/StudentId: historicalBytes: 80
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/StudentId: ID form: PHYSICAL
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/DESFireReader: selectApplication()
2021-04-20 15:15:25.417 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: --> 5A000000 //Is different
2021-04-20 15:15:25.427 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: <-- 00
2021-04-20 15:15:25.427 27336-27373/com.piotrekwitkowski.libraryreader I/StudentId: Application selected: 000000 // is different
2021-04-20 15:15:25.428 27336-27373/com.piotrekwitkowski.libraryreader I/DESFireReader: authenticateAES()
2021-04-20 15:15:25.428 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: --> AA03
2021-04-20 15:15:25.440 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: <-- AFC63BC29AAE3AC13903D3CDF55B72807A
2021-04-20 15:15:25.441 27336-27373/com.piotrekwitkowski.libraryreader I/DESFireReader: challenge: C63BC29AAE3AC13903D3CDF55B72807A
2021-04-20 15:15:25.443 27336-27373/com.piotrekwitkowski.libraryreader I/DESFireReader: cipheredData: 03B55D21CCDC5922803CBC3840ED0740
2021-04-20 15:15:25.444 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: --> AF8EA23EC7209253F7814A9AE54CC61FE3AB91E35AE6B345738D3556FC933A1369
2021-04-20 15:15:25.457 27336-27373/com.piotrekwitkowski.libraryreader I/IsoDep: <-- AE
2021-04-20 15:15:25.457 27336-27373/com.piotrekwitkowski.libraryreader W/System.err: com.piotrekwitkowski.libraryreader.DESFireReaderException: authenticateAES failed
2021-04-20 15:15:25.457 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at com.piotrekwitkowski.libraryreader.DESFireReader.authenticateAES(DESFireReader.java:77)
2021-04-20 15:15:25.457 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at com.piotrekwitkowski.libraryreader.StudentId.authenticateAES(StudentId.java:71)
2021-04-20 15:15:25.457 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at com.piotrekwitkowski.libraryreader.LibraryReader.processTag(LibraryReader.java:33)
2021-04-20 15:15:25.458 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at com.piotrekwitkowski.libraryreader.MainActivity.onTagDiscovered(MainActivity.java:48)
2021-04-20 15:15:25.458 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at android.nfc.NfcActivityManager.onTagDiscovered(NfcActivityManager.java:447)
2021-04-20 15:15:25.458 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at android.nfc.IAppCallback$Stub.onTransact(IAppCallback.java:128)
2021-04-20 15:15:25.458 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1032)
2021-04-20 15:15:25.458 27336-27373/com.piotrekwitkowski.libraryreader W/System.err:     at android.os.Binder.execTransact(Binder.java:1005)`

**Comment by piotrekwitkowski** [comment]
- Can you maybe test your Application with another key? (you are using key #3, there should also be key #0 called also AMK/ Application Master Key) 
- Do you have other DESFire cards or DESFire applications to test the app?

I also had to flip the AID while I was developing the app, but I never had to flip the whole AES key. Sorry for not being able to help!

**Comment by JKorsten** [comment]
Too bad I don't have the AMK. I have other cards, but they also don't work and give the same error.
I think I need to contact the supplier to see if they can help me.

I indeed needed to flip the AID but the AES key I don't know.
No problem, I'm happy that you try to help and I'm very happy with your project and the documentation. Without it I wouldn't get as far as I'm now.

**Comment by JKorsten** [comment]
Just as a repsonse, I found the issue, it was the LIBRARY_KEY_NUMBER I had the wrong value for that.
